### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by BamBam042** [HydroTekZ/BlowableObsidians#1]
Hello , 

I have a problem , can u help me pls ? 

http://pastebin.com/jkdMMCxZ

Good day :)

**Comment by HydroTekZ** [comment]
I actually saw that pastebin before you posted the issue :P

Do you use 1.7, 1.8, 1.9 or 1.10?

I see the jar file is named "BlowableObsidians (1).jar", make sure that you don't have two copies of the plugin. I would recommend renaming "BlowableObsidians (1).jar" to "BlowableObsidians.jar".

And, you do use the latest version of the plugin, right?

**Comment by BamBam042** [comment]
XD I use spigot 1.8.8 last  , i use the last update for ur plugin , and i use mineos ( he use java 1.7 ) i install java 8 for try :)

**Comment by BamBam042** [comment]
It's ok with java 8 , ty my friend <3

**Comment by HydroTekZ** [comment]
No problem :)
