### ISSUE TITLE
Trying to get iron block harder

### ISSUE THREAD

**Issue by SleepingDark** [HydroTekZ/BlowableObsidians#2]
Hy,

When i tryed to use this plugin to get the iron block harder, the one just below the tnt always break.
I try to set the health to 100 and there is no change.
 There is any way to fix it ?

**Comment by HydroTekZ** [comment]
I think I've fixed it now, but I can't actually test it yet (not home).
https://www.dropbox.com/s/u8ghc2kff727h5z/BlowableObsidians.jar?dl=1

**Comment by HydroTekZ** [comment]
It's fixed now in v4.1, but thanks for the feedback :)
