### ISSUE TITLE
I think my server crashed because of  your plugin

### ISSUE THREAD

**Issue by MrRobotMann** [HydroTekZ/BlowableObsidians#3]
Hi,

I Think that my server crashed because of your plugin! 

Crash Report: https://hastebin.com/meliqahawe.md

**Comment by HydroTekZ** [comment]
Do you know what happened before the crash? Could you also send the server log and the config file?

**Comment by MrRobotMann** [comment]
Someone explode 500 tnt blocks inside an obsidian base

**Comment by MrRobotMann** [comment]
Um It crashed again! Please help me solve this problem :/

**Comment by MrRobotMann** [comment]
Here is my config file

https://hastebin.com/selevamaso.coffeescript

**Comment by HydroTekZ** [comment]
Should be fixed in the latest release.
